name: Feature Branch CI
on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "hotfix/*"

jobs:
  tests:
    name: Unit-Tests
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Swift version
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.6.0"
      - name: Run unit tests
        run: |
          swift test --enable-code-coverage
