name: Main Branch CI
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Unit-Tests
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          swift test --enable-code-coverage
  update_documentation:
    name: Update documentation
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          module-name: ConventionalCommitsKit
          output: "docs"
          format: "html"
          base-url: "https://alexanderwe.github.io/ConventionalCommitsKit"
      - name: Commit documentation
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./docs/**
          git commit -m "Generate documentation"
          git push
